
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 12 17:07:02 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREMENT = 31;
  public static final int CONST = 6;
  public static final int EQUALS = 22;
  public static final int CONTINUE = 15;
  public static final int NOTLESS = 25;
  public static final int LESS = 26;
  public static final int MINUS = 18;
  public static final int DECREMENT = 32;
  public static final int OPENPAR = 41;
  public static final int OROR = 29;
  public static final int SEMICOLON = 33;
  public static final int IS = 30;
  public static final int BOOL = 47;
  public static final int CLASS = 4;
  public static final int DIV = 19;
  public static final int ANDAND = 28;
  public static final int DOUBLEDOTS = 34;
  public static final int PLUS = 17;
  public static final int IF = 7;
  public static final int CLOSEPAR = 42;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int MUL = 20;
  public static final int CLOSEBRACKET = 38;
  public static final int PERCENT = 21;
  public static final int NUMBER = 44;
  public static final int IDENT = 46;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int ARROW = 43;
  public static final int FOREACH = 16;
  public static final int ELSE = 5;
  public static final int OPENBRACKET = 37;
  public static final int READ = 11;
  public static final int CHARCONST = 45;
  public static final int NOTEQUALS = 23;
  public static final int WHILE = 8;
  public static final int CLOSEANGLE = 40;
  public static final int FULLSTOP = 36;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int OPENANGLE = 39;
  public static final int NOTMORE = 27;
  public static final int PRINT = 10;
  public static final int MORE = 24;
}

